language: java

jdk:
    - oraclejdk8
    - oraclejdk9
    - oraclejdk11
    - openjdk8
    - openjdk9
    - openjdk10
    - openjdk11
    - openjdk-ea

matrix:
    allow_failures:
        -   jdk: openjdk-ea